[project]
name = "icopage24k"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.4.0",
    "numpy>=2.3.1",
    "pydantic>=2.11.7",
    "ruamel-yaml>=0.18.14",
    "typing-extensions>=4.14.0",
]
